from flask.cli import FlaskGroup
import os

from project import app, connection

cli = FlaskGroup(app)


@cli.command("create_db")
def create_db():
    cursor = connection.cursor()

    # TODO: do we have/how can we implement error checking on this?
    cursor.execute(open("utilities/drop_tables.sql", "r").read())

    print("Creating database...")
    cursor.execute(open("utilities/schema.sql", "r").read())
    connection.commit()
    print("Database created successfully")

# TODO: rewrite function to work on all files in /usr/src/app/data once population is fixed, esp region and country tables
@cli.command("populate_db")
def populate_db():

    cursor = connection.cursor()

    # OPTION 1
    # with open("data/processed_population.csv", 'r') as f:
    #     next(f) # Skip the header row.
    #     cursor.copy_from(f, 'population', sep=',')

    pg_data_path = "/var/lib/postgresql/data/pgdata"

    # load regions
    cursor.execute(f"COPY region FROM '{pg_data_path}/regions.csv' CSV;")
    # load countries
    cursor.execute(f"COPY country FROM '{pg_data_path}/processed_countries.csv' CSV;")

    # TODO: add appropriate volume to db service in docker-compose.yml so Postgres can find the correct csv file.
    # dev notes:
    # all files in services/web/data are meticulously generated by format_csv.py from data in the raw data directory. DO NOT touch this.
    # when running docker, this processed data in the services/web/data directory are copied into /usr/src/app within the container
    # all data is in the correct csv format to be directly imported to their appropriate tables
    # but when using OPTION 1 above that code sets a delimiter ',', which causes issues as there are commas within the data itself
    # so far the best option is to use OPTION 2, but this requires the DBMS to find the location of services/web/data.
    # I trust that this can be fixed by adding the appropriate volume to db service in docker-compose.yml so Postgres can find the correct csv file.

    table_files = [
        ("population", "processed_population.csv"),
        ("gdp", "processed_real_gdp.csv"),
        ("unemployment_rate", "processed_unemployment_rate.csv"),
        ("gini_index", "processed_gini_index.csv"),
        ("area", "processed_area.csv"),
        ("education_expenditure", "processed_education_expenditure.csv")
    ]

    # OPTION 2
    for table, file in table_files:
        print("Creating table for " + file)
        cursor.execute(f"COPY {table} FROM '{pg_data_path}/{file}' CSV;")
    
    connection.commit()
    cursor.close()
    
    print("Tables populated successfully")


# TODO: create makefile script to automatically invoke create_db and populate_db


if __name__ == "__main__":
    cli()
