export const countriesMap = {
  afg: 'Afghanistan',
  alb: 'Albania',
  dza: 'Algeria',
  and: 'Andorra',
  ago: 'Angola',
  atg: 'Antigua and Barbuda',
  arg: 'Argentina',
  arm: 'Armenia',
  aus: 'Australia',
  aut: 'Austria',
  aze: 'Azerbaijan',
  bhs: 'Bahamas',
  bhr: 'Bahrain',
  bgd: 'Bangladesh',
  brb: 'Barbados',
  blr: 'Belarus',
  bel: 'Belgium',
  blz: 'Belize',
  ben: 'Benin',
  btn: 'Bhutan',
  bol: 'Bolivia (Plurinational State of)',
  bih: 'Bosnia and Herzegovina',
  bwa: 'Botswana',
  bra: 'Brazil',
  brn: 'Brunei Darussalam',
  bgr: 'Bulgaria',
  bfa: 'Burkina Faso',
  bdi: 'Burundi',
  cpv: 'Cabo Verde',
  khm: 'Cambodia',
  cmr: 'Cameroon',
  can: 'Canada',
  caf: 'Central African Republic',
  tcd: 'Chad',
  chl: 'Chile',
  chn: 'China',
  col: 'Colombia',
  com: 'Comoros',
  cog: 'Congo',
  cod: 'Congo, Democratic Republic of the',
  cri: 'Costa Rica',
  civ: "Côte d'Ivoire",
  hrv: 'Croatia',
  cub: 'Cuba',
  cyp: 'Cyprus',
  cze: 'Czechia',
  dnk: 'Denmark',
  dji: 'Djibouti',
  dma: 'Dominica',
  dom: 'Dominican Republic',
  ecu: 'Ecuador',
  egy: 'Egypt',
  slv: 'El Salvador',
  gnq: 'Equatorial Guinea',
  eri: 'Eritrea',
  est: 'Estonia',
  swz: 'Eswatini',
  eth: 'Ethiopia',
  fji: 'Fiji',
  fin: 'Finland',
  fra: 'France',
  gab: 'Gabon',
  gmb: 'Gambia',
  geo: 'Georgia',
  deu: 'Germany',
  gha: 'Ghana',
  grc: 'Greece',
  grd: 'Grenada',
  gtm: 'Guatemala',
  gin: 'Guinea',
  gnb: 'Guinea-Bissau',
  guy: 'Guyana',
  hti: 'Haiti',
  hnd: 'Honduras',
  hun: 'Hungary',
  isl: 'Iceland',
  ind: 'India',
  idn: 'Indonesia',
  irn: 'Iran (Islamic Republic of)',
  irq: 'Iraq',
  irl: 'Ireland',
  isr: 'Israel',
  ita: 'Italy',
  jam: 'Jamaica',
  jpn: 'Japan',
  jor: 'Jordan',
  kaz: 'Kazakhstan',
  ken: 'Kenya',
  kir: 'Kiribati',
  prk: "Korea (Democratic People's Republic of)",
  kor: 'Korea, Republic of',
  kwt: 'Kuwait',
  kgz: 'Kyrgyzstan',
  lao: "Lao People's Democratic Republic",
  lva: 'Latvia',
  lbn: 'Lebanon',
  lso: 'Lesotho',
  lbr: 'Liberia',
  lby: 'Libya',
  lie: 'Liechtenstein',
  ltu: 'Lithuania',
  lux: 'Luxembourg',
  mdg: 'Madagascar',
  mwi: 'Malawi',
  mys: 'Malaysia',
  mdv: 'Maldives',
  mli: 'Mali',
  mlt: 'Malta',
  mhl: 'Marshall Islands',
  mrt: 'Mauritania',
  mus: 'Mauritius',
  mex: 'Mexico',
  fsm: 'Micronesia (Federated States of)',
  mda: 'Moldova, Republic of',
  mco: 'Monaco',
  mng: 'Mongolia',
  mne: 'Montenegro',
  mar: 'Morocco',
  moz: 'Mozambique',
  mmr: 'Myanmar',
  nam: 'Namibia',
  nru: 'Nauru',
  npl: 'Nepal',
  nld: 'Netherlands',
  nzl: 'New Zealand',
  nic: 'Nicaragua',
  ner: 'Niger',
  nga: 'Nigeria',
  mkd: 'North Macedonia',
  nor: 'Norway',
  omn: 'Oman',
  pak: 'Pakistan',
  plw: 'Palau',
  pan: 'Panama',
  png: 'Papua New Guinea',
  pry: 'Paraguay',
  per: 'Peru',
  phl: 'Philippines',
  pol: 'Poland',
  prt: 'Portugal',
  qat: 'Qatar',
  rou: 'Romania',
  rus: 'Russian Federation',
  rwa: 'Rwanda',
  kna: 'Saint Kitts and Nevis',
  lca: 'Saint Lucia',
  vct: 'Saint Vincent and the Grenadines',
  wsm: 'Samoa',
  smr: 'San Marino',
  stp: 'Sao Tome and Principe',
  sau: 'Saudi Arabia',
  sen: 'Senegal',
  srb: 'Serbia',
  syc: 'Seychelles',
  sle: 'Sierra Leone',
  sgp: 'Singapore',
  svk: 'Slovakia',
  svn: 'Slovenia',
  slb: 'Solomon Islands',
  som: 'Somalia',
  zaf: 'South Africa',
  ssd: 'South Sudan',
  esp: 'Spain',
  lka: 'Sri Lanka',
  sdn: 'Sudan',
  sur: 'Suriname',
  swe: 'Sweden',
  che: 'Switzerland',
  syr: 'Syrian Arab Republic',
  tjk: 'Tajikistan',
  tza: 'Tanzania, United Republic of',
  tha: 'Thailand',
  tls: 'Timor-Leste',
  tgo: 'Togo',
  ton: 'Tonga',
  tto: 'Trinidad and Tobago',
  tun: 'Tunisia',
  tur: 'Türkiye',
  tkm: 'Turkmenistan',
  tuv: 'Tuvalu',
  uga: 'Uganda',
  ukr: 'Ukraine',
  are: 'United Arab Emirates',
  gbr: 'United Kingdom of Great Britain and Northern Ireland',
  usa: 'United States of America',
  ury: 'Uruguay',
  uzb: 'Uzbekistan',
  vut: 'Vanuatu',
  ven: 'Venezuela (Bolivarian Republic of)',
  vnm: 'Viet Nam',
  yem: 'Yemen',
  zmb: 'Zambia',
  zwe: 'Zimbabwe',
};

export const countryOptions = [
    { key: 'afg', value: 'afg', flag: 'afg', text: 'Afghanistan' },
    { key: 'alb', value: 'alb', flag: 'alb', text: 'Albania' },
    { key: 'dza', value: 'dza', flag: 'dza', text: 'Algeria' },
    { key: 'and', value: 'and', flag: 'and', text: 'Andorra' },
    { key: 'ago', value: 'ago', flag: 'ago', text: 'Angola' },
    { key: 'atg', value: 'atg', flag: 'atg', text: 'Antigua and Barbuda' },
    { key: 'arg', value: 'arg', flag: 'arg', text: 'Argentina' },
    { key: 'arm', value: 'arm', flag: 'arm', text: 'Armenia' },
    { key: 'aus', value: 'aus', flag: 'aus', text: 'Australia' },
    { key: 'aut', value: 'aut', flag: 'aut', text: 'Austria' },
    { key: 'aze', value: 'aze', flag: 'aze', text: 'Azerbaijan' },
    { key: 'bhs', value: 'bhs', flag: 'bhs', text: 'Bahamas' },
    { key: 'bhr', value: 'bhr', flag: 'bhr', text: 'Bahrain' },
    { key: 'bgd', value: 'bgd', flag: 'bgd', text: 'Bangladesh' },
    { key: 'brb', value: 'brb', flag: 'brb', text: 'Barbados' },
    { key: 'blr', value: 'blr', flag: 'blr', text: 'Belarus' },
    { key: 'bel', value: 'bel', flag: 'bel', text: 'Belgium' },
    { key: 'blz', value: 'blz', flag: 'blz', text: 'Belize' },
    { key: 'ben', value: 'ben', flag: 'ben', text: 'Benin' },
    { key: 'btn', value: 'btn', flag: 'btn', text: 'Bhutan' },
    { key: 'bol', value: 'bol', flag: 'bol', text: 'Bolivia (Plurinational State of)' },
    { key: 'bih', value: 'bih', flag: 'bih', text: 'Bosnia and Herzegovina' },
    { key: 'bwa', value: 'bwa', flag: 'bwa', text: 'Botswana' },
    { key: 'bra', value: 'bra', flag: 'bra', text: 'Brazil' },
    { key: 'brn', value: 'brn', flag: 'brn', text: 'Brunei Darussalam' },
    { key: 'bgr', value: 'bgr', flag: 'bgr', text: 'Bulgaria' },
    { key: 'bfa', value: 'bfa', flag: 'bfa', text: 'Burkina Faso' },
    { key: 'bdi', value: 'bdi', flag: 'bdi', text: 'Burundi' },
    { key: 'cpv', value: 'cpv', flag: 'cpv', text: 'Cabo Verde' },
    { key: 'khm', value: 'khm', flag: 'khm', text: 'Cambodia' },
    { key: 'cmr', value: 'cmr', flag: 'cmr', text: 'Cameroon' },
    { key: 'can', value: 'can', flag: 'can', text: 'Canada' },
    { key: 'caf', value: 'caf', flag: 'caf', text: 'Central African Republic' },
    { key: 'tcd', value: 'tcd', flag: 'tcd', text: 'Chad' },
    { key: 'chl', value: 'chl', flag: 'chl', text: 'Chile' },
    { key: 'chn', value: 'chn', flag: 'chn', text: 'China' },
    { key: 'col', value: 'col', flag: 'col', text: 'Colombia' },
    { key: 'com', value: 'com', flag: 'com', text: 'Comoros' },
    { key: 'cog', value: 'cog', flag: 'cog', text: 'Congo' },
    { key: 'cod', value: 'cod', flag: 'cod', text: 'Congo, Democratic Republic of the' },
    { key: 'cri', value: 'cri', flag: 'cri', text: 'Costa Rica' },
    { key: 'civ', value: 'civ', flag: 'civ', text: "Côte d'Ivoire" },
    { key: 'hrv', value: 'hrv', flag: 'hrv', text: 'Croatia' },
    { key: 'cub', value: 'cub', flag: 'cub', text: 'Cuba' },
    { key: 'cyp', value: 'cyp', flag: 'cyp', text: 'Cyprus' },
    { key: 'cze', value: 'cze', flag: 'cze', text: 'Czechia' },
    { key: 'dnk', value: 'dnk', flag: 'dnk', text: 'Denmark' },
    { key: 'dji', value: 'dji', flag: 'dji', text: 'Djibouti' },
    { key: 'dma', value: 'dma', flag: 'dma', text: 'Dominica' },
    { key: 'dom', value: 'dom', flag: 'dom', text: 'Dominican Republic' },
    { key: 'ecu', value: 'ecu', flag: 'ecu', text: 'Ecuador' },
    { key: 'egy', value: 'egy', flag: 'egy', text: 'Egypt' },
    { key: 'slv', value: 'slv', flag: 'slv', text: 'El Salvador' },
    { key: 'gnq', value: 'gnq', flag: 'gnq', text: 'Equatorial Guinea' },
    { key: 'eri', value: 'eri', flag: 'eri', text: 'Eritrea' },
    { key: 'est', value: 'est', flag: 'est', text: 'Estonia' },
    { key: 'swz', value: 'swz', flag: 'swz', text: 'Eswatini' },
    { key: 'eth', value: 'eth', flag: 'eth', text: 'Ethiopia' },
    { key: 'fji', value: 'fji', flag: 'fji', text: 'Fiji' },
    { key: 'fin', value: 'fin', flag: 'fin', text: 'Finland' },
    { key: 'fra', value: 'fra', flag: 'fra', text: 'France' },
    { key: 'gab', value: 'gab', flag: 'gab', text: 'Gabon' },
    { key: 'gmb', value: 'gmb', flag: 'gmb', text: 'Gambia' },
    { key: 'geo', value: 'geo', flag: 'geo', text: 'Georgia' },
    { key: 'deu', value: 'deu', flag: 'deu', text: 'Germany' },
    { key: 'gha', value: 'gha', flag: 'gha', text: 'Ghana' },
    { key: 'grc', value: 'grc', flag: 'grc', text: 'Greece' },
    { key: 'grd', value: 'grd', flag: 'grd', text: 'Grenada' },
    { key: 'gtm', value: 'gtm', flag: 'gtm', text: 'Guatemala' },
    { key: 'gin', value: 'gin', flag: 'gin', text: 'Guinea' },
    { key: 'gnb', value: 'gnb', flag: 'gnb', text: 'Guinea-Bissau' },
    { key: 'guy', value: 'guy', flag: 'guy', text: 'Guyana' },
    { key: 'hti', value: 'hti', flag: 'hti', text: 'Haiti' },
    { key: 'hnd', value: 'hnd', flag: 'hnd', text: 'Honduras' },
    { key: 'hun', value: 'hun', flag: 'hun', text: 'Hungary' },
    { key: 'isl', value: 'isl', flag: 'isl', text: 'Iceland' },
    { key: 'ind', value: 'ind', flag: 'ind', text: 'India' },
    { key: 'idn', value: 'idn', flag: 'idn', text: 'Indonesia' },
    { key: 'irn', value: 'irn', flag: 'irn', text: 'Iran (Islamic Republic of)' },
    { key: 'irq', value: 'irq', flag: 'irq', text: 'Iraq' },
    { key: 'irl', value: 'irl', flag: 'irl', text: 'Ireland' },
    { key: 'isr', value: 'isr', flag: 'isr', text: 'Israel' },
    { key: 'ita', value: 'ita', flag: 'ita', text: 'Italy' },
    { key: 'jam', value: 'jam', flag: 'jam', text: 'Jamaica' },
    { key: 'jpn', value: 'jpn', flag: 'jpn', text: 'Japan' },
    { key: 'jor', value: 'jor', flag: 'jor', text: 'Jordan' },
    { key: 'kaz', value: 'kaz', flag: 'kaz', text: 'Kazakhstan' },
    { key: 'ken', value: 'ken', flag: 'ken', text: 'Kenya' },
    { key: 'kir', value: 'kir', flag: 'kir', text: 'Kiribati' },
    { key: 'prk', value: 'prk', flag: 'prk', text: "Korea (Democratic People's Republic of)" },
    { key: 'kor', value: 'kor', flag: 'kor', text: 'Korea, Republic of' },
    { key: 'kwt', value: 'kwt', flag: 'kwt', text: 'Kuwait' },
    { key: 'kgz', value: 'kgz', flag: 'kgz', text: 'Kyrgyzstan' },
    { key: 'lao', value: 'lao', flag: 'lao', text: "Lao People's Democratic Republic" },
    { key: 'lva', value: 'lva', flag: 'lva', text: 'Latvia' },
    { key: 'lbn', value: 'lbn', flag: 'lbn', text: 'Lebanon' },
    { key: 'lso', value: 'lso', flag: 'lso', text: 'Lesotho' },
    { key: 'lbr', value: 'lbr', flag: 'lbr', text: 'Liberia' },
    { key: 'lby', value: 'lby', flag: 'lby', text: 'Libya' },
    { key: 'lie', value: 'lie', flag: 'lie', text: 'Liechtenstein' },
    { key: 'ltu', value: 'ltu', flag: 'ltu', text: 'Lithuania' },
    { key: 'lux', value: 'lux', flag: 'lux', text: 'Luxembourg' },
    { key: 'mdg', value: 'mdg', flag: 'mdg', text: 'Madagascar' },
    { key: 'mwi', value: 'mwi', flag: 'mwi', text: 'Malawi' },
    { key: 'mys', value: 'mys', flag: 'mys', text: 'Malaysia' },
    { key: 'mdv', value: 'mdv', flag: 'mdv', text: 'Maldives' },
    { key: 'mli', value: 'mli', flag: 'mli', text: 'Mali' },
    { key: 'mlt', value: 'mlt', flag: 'mlt', text: 'Malta' },
    { key: 'mhl', value: 'mhl', flag: 'mhl', text: 'Marshall Islands' },
    { key: 'mrt', value: 'mrt', flag: 'mrt', text: 'Mauritania' },
    { key: 'mus', value: 'mus', flag: 'mus', text: 'Mauritius' },
    { key: 'mex', value: 'mex', flag: 'mex', text: 'Mexico' },
    { key: 'fsm', value: 'fsm', flag: 'fsm', text: 'Micronesia (Federated States of)' },
    { key: 'mda', value: 'mda', flag: 'mda', text: 'Moldova, Republic of' },
    { key: 'mco', value: 'mco', flag: 'mco', text: 'Monaco' },
    { key: 'mng', value: 'mng', flag: 'mng', text: 'Mongolia' },
    { key: 'mne', value: 'mne', flag: 'mne', text: 'Montenegro' },
    { key: 'mar', value: 'mar', flag: 'mar', text: 'Morocco' },
    { key: 'moz', value: 'moz', flag: 'moz', text: 'Mozambique' },
    { key: 'mmr', value: 'mmr', flag: 'mmr', text: 'Myanmar' },
    { key: 'nam', value: 'nam', flag: 'nam', text: 'Namibia' },
    { key: 'nru', value: 'nru', flag: 'nru', text: 'Nauru' },
    { key: 'npl', value: 'npl', flag: 'npl', text: 'Nepal' },
    { key: 'nld', value: 'nld', flag: 'nld', text: 'Netherlands' },
    { key: 'nzl', value: 'nzl', flag: 'nzl', text: 'New Zealand' },
    { key: 'nic', value: 'nic', flag: 'nic', text: 'Nicaragua' },
    { key: 'ner', value: 'ner', flag: 'ner', text: 'Niger' },
    { key: 'nga', value: 'nga', flag: 'nga', text: 'Nigeria' },
    { key: 'mkd', value: 'mkd', flag: 'mkd', text: 'North Macedonia' },
    { key: 'nor', value: 'nor', flag: 'nor', text: 'Norway' },
    { key: 'omn', value: 'omn', flag: 'omn', text: 'Oman' },
    { key: 'pak', value: 'pak', flag: 'pak', text: 'Pakistan' },
    { key: 'plw', value: 'plw', flag: 'plw', text: 'Palau' },
    { key: 'pan', value: 'pan', flag: 'pan', text: 'Panama' },
    { key: 'png', value: 'png', flag: 'png', text: 'Papua New Guinea' },
    { key: 'pry', value: 'pry', flag: 'pry', text: 'Paraguay' },
    { key: 'per', value: 'per', flag: 'per', text: 'Peru' },
    { key: 'phl', value: 'phl', flag: 'phl', text: 'Philippines' },
    { key: 'pol', value: 'pol', flag: 'pol', text: 'Poland' },
    { key: 'prt', value: 'prt', flag: 'prt', text: 'Portugal' },
    { key: 'qat', value: 'qat', flag: 'qat', text: 'Qatar' },
    { key: 'rou', value: 'rou', flag: 'rou', text: 'Romania' },
    { key: 'rus', value: 'rus', flag: 'rus', text: 'Russian Federation' },
    { key: 'rwa', value: 'rwa', flag: 'rwa', text: 'Rwanda' },
    { key: 'kna', value: 'kna', flag: 'kna', text: 'Saint Kitts and Nevis' },
    { key: 'lca', value: 'lca', flag: 'lca', text: 'Saint Lucia' },
    { key: 'vct', value: 'vct', flag: 'vct', text: 'Saint Vincent and the Grenadines' },
    { key: 'wsm', value: 'wsm', flag: 'wsm', text: 'Samoa' },
    { key: 'smr', value: 'smr', flag: 'smr', text: 'San Marino' },
    { key: 'stp', value: 'stp', flag: 'stp', text: 'Sao Tome and Principe' },
    { key: 'sau', value: 'sau', flag: 'sau', text: 'Saudi Arabia' },
    { key: 'sen', value: 'sen', flag: 'sen', text: 'Senegal' },
    { key: 'srb', value: 'srb', flag: 'srb', text: 'Serbia' },
    { key: 'syc', value: 'syc', flag: 'syc', text: 'Seychelles' },
    { key: 'sle', value: 'sle', flag: 'sle', text: 'Sierra Leone' },
    { key: 'sgp', value: 'sgp', flag: 'sgp', text: 'Singapore' },
    { key: 'svk', value: 'svk', flag: 'svk', text: 'Slovakia' },
    { key: 'svn', value: 'svn', flag: 'svn', text: 'Slovenia' },
    { key: 'slb', value: 'slb', flag: 'slb', text: 'Solomon Islands' },
    { key: 'som', value: 'som', flag: 'som', text: 'Somalia' },
    { key: 'zaf', value: 'zaf', flag: 'zaf', text: 'South Africa' },
    { key: 'ssd', value: 'ssd', flag: 'ssd', text: 'South Sudan' },
    { key: 'esp', value: 'esp', flag: 'esp', text: 'Spain' },
    { key: 'lka', value: 'lka', flag: 'lka', text: 'Sri Lanka' },
    { key: 'sdn', value: 'sdn', flag: 'sdn', text: 'Sudan' },
    { key: 'sur', value: 'sur', flag: 'sur', text: 'Suriname' },
    { key: 'swe', value: 'swe', flag: 'swe', text: 'Sweden' },
    { key: 'che', value: 'che', flag: 'che', text: 'Switzerland' },
    { key: 'syr', value: 'syr', flag: 'syr', text: 'Syrian Arab Republic' },
    { key: 'tjk', value: 'tjk', flag: 'tjk', text: 'Tajikistan' },
    { key: 'tza', value: 'tza', flag: 'tza', text: 'Tanzania, United Republic of' },
    { key: 'tha', value: 'tha', flag: 'tha', text: 'Thailand' },
    { key: 'tls', value: 'tls', flag: 'tls', text: 'Timor-Leste' },
    { key: 'tgo', value: 'tgo', flag: 'tgo', text: 'Togo' },
    { key: 'ton', value: 'ton', flag: 'ton', text: 'Tonga' },
    { key: 'tto', value: 'tto', flag: 'tto', text: 'Trinidad and Tobago' },
    { key: 'tun', value: 'tun', flag: 'tun', text: 'Tunisia' },
    { key: 'tur', value: 'tur', flag: 'tur', text: 'Türkiye' },
    { key: 'tkm', value: 'tkm', flag: 'tkm', text: 'Turkmenistan' },
    { key: 'tuv', value: 'tuv', flag: 'tuv', text: 'Tuvalu' },
    { key: 'uga', value: 'uga', flag: 'uga', text: 'Uganda' },
    { key: 'ukr', value: 'ukr', flag: 'ukr', text: 'Ukraine' },
    { key: 'are', value: 'are', flag: 'are', text: 'United Arab Emirates' },
    { key: 'gbr', value: 'gbr', flag: 'gbr', text: 'United Kingdom of Great Britain and Northern Ireland' },
    { key: 'usa', value: 'usa', flag: 'usa', text: 'United States of America' },
    { key: 'ury', value: 'ury', flag: 'ury', text: 'Uruguay' },
    { key: 'uzb', value: 'uzb', flag: 'uzb', text: 'Uzbekistan' },
    { key: 'vut', value: 'vut', flag: 'vut', text: 'Vanuatu' },
    { key: 'ven', value: 'ven', flag: 'ven', text: 'Venezuela (Bolivarian Republic of)' },
    { key: 'vnm', value: 'vnm', flag: 'vnm', text: 'Viet Nam' },
    { key: 'yem', value: 'yem', flag: 'yem', text: 'Yemen' },
    { key: 'zmb', value: 'zmb', flag: 'zmb', text: 'Zambia' },
    { key: 'zwe', value: 'zwe', flag: 'zwe', text: 'Zimbabwe' },
];
