DROP TABLE IF EXISTS Area;
DROP TABLE IF EXISTS Country CASCADE;
DROP TABLE IF EXISTS Education_Expenditure;
DROP TABLE IF EXISTS Games;
DROP TABLE IF EXISTS GDP;
DROP TABLE IF EXISTS Gini_Index;
DROP TABLE IF EXISTS Population;
DROP TABLE IF EXISTS Region;
DROP TABLE IF EXISTS Unemployment_Rate;
DROP TABLE IF EXISTS Users;

-- DROP TABLE IF EXISTS Gdp_in;